language: python

python:
  - "2.7"

virtualenv: 
  system_site_packages: true

install:
  - sudo apt-get update
  - sudo apt-get install python-numpy
  - sudo apt-get install python-scipy
  - sudo apt-get install python-matplotlib
  - sudo apt-get install cython
  - pip install matplotlib scikit-image
  - pip install .

script:
  - nosetests yoink

